# Generated by Django 4.2.13 on 2024-06-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='Camera',
            new_name='camera',
        ),
    ]
