# Generated by Django 4.2.13 on 2024-06-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_rename_camera_phone_camera'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reference',
            new_name='Model',
        ),
    ]
